[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
local = "${RPC_URL}"
sepolia = "https://rpc.ankr.com/eth_sepolia"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
